import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:ui';

enum AppLanguage { fr, en, ar }

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  AppLanguage _currentLanguage = AppLanguage.fr;
  static const String _langKey = 'selected_language';

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLang = prefs.getString(_langKey);

    if (savedLang != null) {
      _currentLanguage = AppLanguage.values.firstWhere(
        (e) => e.toString() == savedLang,
        orElse: () => AppLanguage.en,
      );
    } else {
      // Détection automatique de la langue du système
      final String systemLang = PlatformDispatcher.instance.locale.languageCode;
      if (systemLang == 'fr') {
        _currentLanguage = AppLanguage.fr;
      } else if (systemLang == 'ar') {
        _currentLanguage = AppLanguage.ar;
      } else {
        _currentLanguage = AppLanguage.en;
      }
      // Sauvegarder pour la prochaine fois
      await prefs.setString(_langKey, _currentLanguage.toString());
    }
    notifyListeners();
  }

  AppLanguage get currentLanguage => _currentLanguage;

  bool get isRTL => _currentLanguage == AppLanguage.ar;

  Future<void> setLanguage(AppLanguage lang) async {
    print("🌍 Changement de langue demandé : $lang");
    if (_currentLanguage != lang) {
      _currentLanguage = lang;
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_langKey, lang.toString());
      print("✅ Langue sauvegardée : $lang");
      notifyListeners();
    }
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  static const Map<AppLanguage, Map<String, String>> _translations = {
    AppLanguage.fr: {
      'loading': 'Chargement des mots...',
      'play': 'Jouer',
      'adventure_mode': 'MODE AVENTURE',
      'adventure_subtitle': 'RELEVEZ LE DÉFI DE LA SAGA DES MOTS',
      'classic_mode': 'CLASSIQUE',
      'classic_subtitle': 'Lingo standard',
      'duel_mode': 'DUEL',
      'duel_subtitle': 'Multijoueur',
      'coming_soon': 'BIENTÔT',
      'settings': 'Paramètres',
      'language': 'Langue',
      'sound': 'Sons',
      'haptics': 'Vibrations',
      'lives': 'VIES',
      'streak': 'STREAK',
      'not_in_dict': 'Mot inconnu',
      'too_short': 'Mot trop court',
      'win': 'Bravo !',
      'lose': 'Perdu ! Le mot était',
      'next_life': 'Prochaine vie dans',
      'watch_ad': 'Regarder une pub (+1 vie)',
      'daily_reward': 'DÉFI QUOTIDIEN',
      'best_score': 'RECORD',
      'shop': 'BOUTIQUE',
      'leaderboard': 'CLASSEMENT',
      'rank': 'RANG',
      'balance': 'Solde actuel',
      'buy': 'Acheter',
      'mondial': 'MONDIAL',
      'local': 'LOCAL',
      'daily_reward_title': 'RÉCOMPENSE JOURNALIÈRE',
      'daily_reward_subtitle': 'Connectez-vous chaque jour pour gagner plus !',
      'claim_reward': 'RÉCUPÉRER MON CADEAU',
      'come_back_tomorrow': 'REVIENS DEMAIN !',
      'reward_claimed': 'Récompense récupérée ! 🎉',
      'choose_challenge': 'CHOISISSEZ VOTRE DÉFI',
      'find_word_subtitle': 'Trouvez le mot secret en un minimum d\'essais',
      'easy_word': 'PETIT MOT',
      'normal_word': 'CLASSIQUE',
      'hard_word': 'EXPERT',
      'letters_attempts': '{n} LETTRES • {a} ESSAIS',
      'searching_opponent': 'RECHERCHE D\'UN ADVERSAIRE...',
      'cancel': 'ANNULER',
      'no_opponent_title': 'AUCUN ADVERSAIRE',
      'no_opponent_body': 'Personne n\'est en ligne pour le moment. Réessaye plus tard !',
      'you': 'VOUS',
      'duel_win_reward': 'LE PREMIER QUI TROUVE LE MOT GAGNE 200 PIÈCES !',
      'find_match': 'TROUVER UN MATCH',
      'saga_subtitle': 'SAGA DES MOTS',
      'difficulty_easy': 'FACILE',
      'difficulty_medium': 'MOYEN',
      'difficulty_hard': 'DIFFICILE',
      'n_letters': '{n} LETTRES',
      'watch_ad_menu': 'Regarder une vidéo',
      'free': 'GRATUIT',
      'small_pack': 'Pack Débutant',
      'medium_pack': 'Pack Expert',
      'large_pack': 'Pack Maître',
      'infinite_lives_short': 'Vies Infinies (2h)',
      'infinite_lives_long': 'Vies Infinies (24h)',
      'infinite_lives_2h': '2H INFINI',
      'infinite_lives_24h': '24H INFINI',
      'boosters': 'BOOSTERS',
      'coins': 'PIÈCES',
      'no_scores': 'Aucun score trouvé',
      'app_subtitle': 'L\'ULTIME DÉFI LINGUISTIQUE',
      'play_menu': 'JOUER',
      'shop_menu': 'BOUTIQUE',
      'shop_subtitle': 'OBTENEZ DES PIÈCES ET BOOSTERS',
      'account': 'COMPTE',
      'notifications': 'NOTIFICATIONS',
      'legal': 'LÉGAL',
      'privacy': 'Confidentialité',
      'terms': 'Conditions',
      'logout': 'DÉCONNEXION',
      'cloud_sync': 'SYNCHRONISATION CLOUD',
      'total_streak': 'SÉRIE TOTALE',
      'joined': 'Inscrit en',
      'you_abandoned': 'Vous avez abandonné.',
      'opponent_abandoned': 'L\'adversaire a abandonné ! Vous gagnez !',
      'purchase_title': 'Achat In-App',
      'purchase_body': 'Voulez-vous simuler l\'achat de {amount} pour {price} ?',
      'purchase_success': 'Achat réussi ! +{amount}',
      'booster_title': 'Booster de Vies',
      'booster_body': 'Voulez-vous simuler l\'achat de vies infinies ({hours}h) pour {price} ?',
      'booster_success': 'Booster activé ! Vies infinies pendant {hours}h',
      'confirm': 'Acheter',
      'ad_title': 'Publicité',
      'ad_body': 'Lecture de la vidéo...',
      'confirm_abandon': 'Voulez-vous vraiment abandonner la partie ?',
      'yes_abandon': 'OUI, ABANDONNER',
      'no': 'NON',
      'news_1': 'EN DIRECT : {name} VIENT DE DÉBLOQUER LE NIVEAU {level} !',
      'news_2': 'NOUVELLE SAISON DANS {days} JOURS !',
      'news_3': 'ÉVÉNEMENT : +200% DE COINS DANS LE MODE DUEL !',
      'you_indicator': 'VOUS',
    },
    AppLanguage.en: {
      'loading': 'Loading words...',
      'play': 'Play',
      'adventure_mode': 'ADVENTURE MODE',
      'adventure_subtitle': 'TAKE ON THE WORD SAGA CHALLENGE',
      'classic_mode': 'CLASSIC',
      'classic_subtitle': 'Standard Lingo',
      'duel_mode': 'DUEL',
      'duel_subtitle': 'Multiplayer',
      'coming_soon': 'COMING SOON',
      'settings': 'Settings',
      'language': 'Language',
      'sound': 'Sound',
      'haptics': 'Haptics',
      'lives': 'LIVES',
      'streak': 'STREAK',
      'not_in_dict': 'Not in dictionary',
      'too_short': 'Word too short',
      'win': 'Well done!',
      'lose': 'Game Over! The word was',
      'next_life': 'Next life in',
      'watch_ad': 'Watch Ad (+1 life)',
      'daily_reward': 'DAILY CHALLENGE',
      'best_score': 'BEST SCORE',
      'shop': 'SHOP',
      'leaderboard': 'LEADERBOARD',
      'rank': 'RANK',
      'balance': 'Current balance',
      'buy': 'Buy',
      'mondial': 'WORLDWIDE',
      'local': 'LOCAL',
      'daily_reward_title': 'DAILY REWARD',
      'daily_reward_subtitle': 'Connect every day to win more!',
      'claim_reward': 'CLAIM MY GIFT',
      'come_back_tomorrow': 'COME BACK TOMORROW!',
      'reward_claimed': 'Reward claimed! 🎉',
      'choose_challenge': 'CHOOSE YOUR CHALLENGE',
      'find_word_subtitle': 'Find the secret word in minimum attempts',
      'easy_word': 'SMALL WORD',
      'normal_word': 'CLASSIC',
      'hard_word': 'EXPERT',
      'letters_attempts': '{n} LETTERS • {a} ATTEMPTS',
      'searching_opponent': 'SEARCHING FOR OPPONENT...',
      'cancel': 'CANCEL',
      'no_opponent_title': 'NO OPPONENT',
      'no_opponent_body': 'Nobody is online right now. Try again later!',
      'you': 'YOU',
      'duel_win_reward': 'FIRST TO FIND THE WORD WINS 200 COINS!',
      'find_match': 'FIND A MATCH',
      'saga_subtitle': 'WORD SAGA',
      'difficulty_easy': 'EASY',
      'difficulty_medium': 'MEDIUM',
      'difficulty_hard': 'HARD',
      'n_letters': '{n} LETTERS',
      'watch_ad_menu': 'Watch a video',
      'free': 'FREE',
      'small_pack': 'Starter Pack',
      'medium_pack': 'Expert Pack',
      'large_pack': 'Master Pack',
      'infinite_lives_short': 'Infinite Lives (2h)',
      'infinite_lives_long': 'Infinite Lives (24h)',
      'infinite_lives_2h': '2H INFINITE',
      'infinite_lives_24h': '24H INFINITE',
      'boosters': 'BOOSTERS',
      'coins': 'COINS',
      'no_scores': 'No scores found',
      'app_subtitle': 'THE ULTIMATE LINGUISTIC CHALLENGE',
      'play_menu': 'PLAY',
      'shop_menu': 'SHOP',
      'shop_subtitle': 'GET COINS AND BOOSTERS',
      'account': 'ACCOUNT',
      'notifications': 'NOTIFICATIONS',
      'legal': 'LEGAL',
      'privacy': 'Privacy',
      'terms': 'Terms',
      'logout': 'LOG OUT',
      'cloud_sync': 'CLOUD SYNC',
      'total_streak': 'TOTAL STREAK',
      'joined': 'Joined',
      'you_abandoned': 'You abandoned the match.',
      'opponent_abandoned': 'Opponent abandoned! You win!',
      'purchase_title': 'In-App Purchase',
      'purchase_body': 'Do you want to simulate the purchase of {amount} for {price}?',
      'purchase_success': 'Purchase successful! +{amount}',
      'booster_title': 'Life Booster',
      'booster_body': 'Do you want to simulate the purchase of infinite lives ({hours}h) for {price}?',
      'booster_success': 'Booster activated! Infinite lives for {hours}h',
      'confirm': 'Buy',
      'ad_title': 'Advertisement',
      'ad_body': 'Playing video...',
      'confirm_abandon': 'Do you really want to abandon the match?',
      'yes_abandon': 'YES, ABANDON',
      'no': 'NO',
      'news_1': 'LIVE: {name} JUST UNLOCKED LEVEL {level}!',
      'news_2': 'NEW SEASON IN {days} DAYS!',
      'news_3': 'EVENT: +200% COINS IN DUEL MODE!',
      'you_indicator': 'YOU',
    },
    AppLanguage.ar: {
      'loading': 'جاري تحميل الكلمات...',
      'play': 'العب',
      'adventure_mode': 'وضع المغامرة',
      'adventure_subtitle': 'واجه تحدي ملحمة الكلمات',
      'classic_mode': 'كلاسيكي',
      'classic_subtitle': 'لينغو قياسي',
      'duel_mode': 'مبارزة',
      'duel_subtitle': 'متعدد اللاعبين',
      'coming_soon': 'قريباً',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'sound': 'الصوت',
      'haptics': 'الاهتزاز',
      'lives': 'حياة',
      'streak': 'سلسلة',
      'not_in_dict': 'الكلمة غير موجودة',
      'too_short': 'الكلمة قصيرة جداً',
      'win': 'أحسنت!',
      'lose': 'خسرت! الكلمة كانت',
      'next_life': 'الحياة القامدة في',
      'watch_ad': 'شاهد إعلان (+1 حياة)',
      'daily_reward': 'التحدي اليومي',
      'best_score': 'أفضل نتيجة',
      'shop': 'المتجر',
      'leaderboard': 'ترتيب اللاعبين',
      'rank': 'رتبتك',
      'balance': 'الرصid الحالي',
      'buy': 'شراء',
      'mondial': 'عالمي',
      'local': 'محلي',
      'daily_reward_title': 'المكافأة اليومية',
      'daily_reward_subtitle': 'سجل دخولك يومياً لتربح أكثر!',
      'claim_reward': 'احصل على هديتي',
      'come_back_tomorrow': 'عد غداً!',
      'reward_claimed': 'تم استلام المكافأة! 🎉',
      'choose_challenge': 'اختر تحديك',
      'find_word_subtitle': 'جد الكلمة السرية في أقل عدد من المحاولات',
      'easy_word': 'كلمة قصيرة',
      'normal_word': 'كلاسيكي',
      'hard_word': 'خبير',
      'letters_attempts': '{n} أحرف • {a} محاولات',
      'searching_opponent': 'جاري البحث عن خصم...',
      'cancel': 'إلغاء',
      'no_opponent_title': 'لا يوجد خصم',
      'no_opponent_body': 'لا يوجد أحد متصل حالياً. حاول لاحقاً!',
      'you': 'أنت',
      'duel_win_reward': 'أول من يجد الكلمة يربح 200 قطعة!',
      'find_match': 'البحث عن مباراة',
      'saga_subtitle': 'ملحمة الكلمات',
      'difficulty_easy': 'سهل',
      'difficulty_medium': 'متوسط',
      'difficulty_hard': 'صعب',
      'n_letters': '{n} حروف',
      'watch_ad_menu': 'شاهد فيديو',
      'free': 'مجاني',
      'small_pack': 'باقة المبتدئين',
      'medium_pack': 'باقة الخبراء',
      'large_pack': 'باقة المحترفين',
      'infinite_lives_short': 'حياة غير محدودة (2س)',
      'infinite_lives_long': 'حياة غير محدودة (24س)',
      'infinite_lives_2h': '2س غير محدود',
      'infinite_lives_24h': '24س غير محدود',
      'boosters': 'المعززات',
      'coins': 'العملات',
      'no_scores': 'لم يتم العثور على نتائج',
      'app_subtitle': 'تحدي الكلمات النهائي',
      'play_menu': 'العب',
      'shop_menu': 'المتجر',
      'shop_subtitle': 'احصل على عملات ومعززات',
      'account': 'الحساب',
      'notifications': 'التنبيهات',
      'legal': 'قانوني',
      'privacy': 'الخصوصية',
      'terms': 'الشروط',
      'logout': 'تسجيل الخروج',
      'cloud_sync': 'مزامنة السحابة',
      'total_streak': 'السلسلة الإجمالية',
      'joined': 'انضم في',
      'you_abandoned': 'لقد انسحبت من المباراة.',
      'opponent_abandoned': 'انسحب الخصم! لقد فزت!',
      'purchase_title': 'شراء داخل التطبيق',
      'purchase_body': 'هل تريد محاكاة شراء {amount} مقابل {price}؟',
      'purchase_success': 'تم الشراء بنجاح! +{amount}',
      'booster_title': 'معزز الحياة',
      'booster_body': 'هل تريد محاكاة شراء حياة غير محدودة ({hours}س) مقابل {price}؟',
      'booster_success': 'تم تفعيل المعزز! حياة غير محدودة لمدة {hours}س',
      'confirm': 'شراء',
      'ad_title': 'إعلان',
      'ad_body': 'جاري تشغيل الفيديو...',
      'confirm_abandon': 'هل تريد حقًا الانسحاب من المباراة؟',
      'yes_abandon': 'نعم، انسحاب',
      'no': 'لا',
      'news_1': 'مباشر: {name} فتح المستوى {level} للتو!',
      'news_2': 'الموسم الجديد يبدأ خلال {days} أيام!',
      'news_3': 'حدث: +200% عملات في وضع المبارزة!',
      'you_indicator': 'أنت',
    },
  };
}
