// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmWv_TVTwAL1SrmqeSgcYRMT6citjFu4',
    appId: '1:541586682501:web:c7119d525f9300b1d9afec',
    messagingSenderId: '541586682501',
    projectId: 'wordsnap-6ef7a',
    authDomain: 'wordsnap-6ef7a.firebaseapp.com',
    storageBucket: 'wordsnap-6ef7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzdyUYCsAqoRDm7P_I77549xf5ysNvyQ',
    appId: '1:541586682501:android:e640c86fe6263816d9afec',
    messagingSenderId: '541586682501',
    projectId: 'wordsnap-6ef7a',
    storageBucket: 'wordsnap-6ef7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSb2jEJToODyyjP3ePiXjMpY_pdJYvIZk',
    appId: '1:541586682501:ios:9acb10d0af9a1491d9afec',
    messagingSenderId: '541586682501',
    projectId: 'wordsnap-6ef7a',
    storageBucket: 'wordsnap-6ef7a.firebasestorage.app',
    iosBundleId: 'com.example.wordsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSb2jEJToODyyjP3ePiXjMpY_pdJYvIZk',
    appId: '1:541586682501:ios:9acb10d0af9a1491d9afec',
    messagingSenderId: '541586682501',
    projectId: 'wordsnap-6ef7a',
    storageBucket: 'wordsnap-6ef7a.firebasestorage.app',
    iosBundleId: 'com.example.wordsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkmWv_TVTwAL1SrmqeSgcYRMT6citjFu4',
    appId: '1:541586682501:web:c75bc2cb9e3fd707d9afec',
    messagingSenderId: '541586682501',
    projectId: 'wordsnap-6ef7a',
    authDomain: 'wordsnap-6ef7a.firebaseapp.com',
    storageBucket: 'wordsnap-6ef7a.firebasestorage.app',
  );
}
